### ISSUE TITLE
Staff

### ISSUE THREAD

**Issue by j-bresson** [ramagottfried/symbolist#25]
Add the staff layer between PageComponent and SymbolComponent

**Comment by ramagottfried** [comment]
just committed first working version -- but it's not a layer between the Page and Symbol components yet.

at the moment the working method is:
1) make a staff and give it a name in the inspector
2) make a symbol and set the staff field to be the name of the staff, this will then cause the score to create time points for this symbol

It would be nice to make a "map mode" (like Live's MIDI map mode), for connecting symbols with a staff. This might be a button in the /staff field in the inspector, which allows the user to then click on a staff and fill the /staff field automatically.

**Comment by ramagottfried** [comment]
added a popup menu in the inspector where you can select from existing staff objects.

we might want to create a staff-edit mode where you can select and move staves. 
in normal edit mode, the staff should probably be locked in place, and ignored by the lasso tool.

**Comment by ramagottfried** [comment]
new version of staff system, now *is* a layer between Page and Symbol (basically a type of group).

also added staff selection mode (still needs some tweaking though).
