### ISSUE TITLE
when a change on a 'shape' symbol is made in the inspector a duplicated path is created in the Symbol

### ISSUE THREAD

**Issue by j-bresson** [ramagottfried/symbolist#38]

**Comment by ramagottfried** [comment]
fixed

**Comment by ramagottfried** [comment]
actually, fixed for edited basic shapes (where basic shapes become paths), but not for un-edited basic shapes...

**Comment by ramagottfried** [comment]
ok fixed by clearing paths before importing in basic shapes

**Comment by ramagottfried** [comment]
there was also a problem with the group import symbol where the subcomponents were not being cleared -- now fixed.
