### ISSUE TITLE
bounding box of Path

### ISSUE THREAD

**Issue by j-bresson** [ramagottfried/symbolist#40]
... still needs some work.

The Sym_PathBounds seems ok but the resize functions include the cubic/quadratic control point in the bounds

**Comment by ramagottfried** [comment]
fixed for resizing, flips are still broken

**Comment by ramagottfried** [comment]
fixed flips

**Comment by ramagottfried** [comment]
(also just fixed the resize to fit x/y offset, still not perfect, but closer)
