### ISSUE TITLE
grouping

### ISSUE THREAD

**Issue by ramagottfried** [ramagottfried/symbolist#5]
re question in ScoreComponent: https://github.com/j-bresson/symbolist/blob/master/Source/ScoreComponent.cpp#L133

j: DOES THIS REMOVES THE COMPONENT FROM ITS ORIGINAL CONTAINER ??
r: no I don't think so, the memory is still in the score_stack

**Comment by j-bresson** [comment]
... making this a general issue about grouping/ungrouping components
todos:
- finish/cleanup the operations on the GUI side
- apply to score (i.e. encode/decode groups as OSC bundmes)
- allow opreations (add/delete etc.) within a group

**Comment by j-bresson** [comment]
Commit https://github.com/j-bresson/symbolist/commit/772386576ec20e559b9d0ddc715ea5252314d845

Current state = grouping works _but_
- memory management not ok (leaks / crashes at quitting the app / lib)
- score updates not ok (crashes when groups are created / modifed in OM)

TODOs:
- ungrouping the group
- add-symbol inside the group

**Comment by j-bresson** [comment]
https://github.com/j-bresson/symbolist/commit/aef4be8994bf72e056a4a3809c014467bf8d99b5
=> fixes memory leak

- score updates still not ok (crashes when groups are created / modifed in OM)

TODOs:
- un-grouping the group
- add-symbol inside the group
- moving symbols in group => update bounds

**Comment by j-bresson** [comment]
done :-p
