### ISSUE TITLE
time and rendering

### ISSUE THREAD

**Issue by j-bresson** [ramagottfried/symbolist#6]
=> add a time attribute to the symbols (+ duration?)
=> set a 'current-time' global variable displayed in the score
- as a cursor-like graphic element, or
- as a specific highlight on symbols at current time

**Comment by j-bresson** [comment]
In the OM side (or host environment in general) : use the scheduling system to 'play' the symbolis score, i.e.
- send periodic time update to the viewer
- send out the stream of OSC bundles

**Comment by ramagottfried** [comment]
I'm pretty sure this is all functional
